// <auto-generated />
using System;
using Auction.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Auction.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20190226080743_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Auction.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Guid");

                    b.Property<string>("AuctionHouse")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("CreatedByUserGuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<decimal?>("DealPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("DealPriceRMB")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("Height");

                    b.Property<int?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("IsPurchase");

                    b.Property<int>("IsSold")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("Long");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ModifiedByUserGuid");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ProductionDate");

                    b.Property<string>("UseType");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<double?>("Weight");

                    b.Property<int?>("Width");

                    b.Property<DateTime?>("WorkingTime");

                    b.HasKey("Guid");

                    b.ToTable("ac_equipment");
                });

            modelBuilder.Entity("Auction.Entities.EquipmentPhoto", b =>
                {
                    b.Property<Guid>("EquipmentGuid");

                    b.Property<Guid>("PhotoGuid");

                    b.Property<DateTime?>("CreatedOn");

                    b.HasKey("EquipmentGuid", "PhotoGuid");

                    b.HasIndex("PhotoGuid");

                    b.ToTable("ac_equipment_photo");
                });

            modelBuilder.Entity("Auction.Entities.Photo", b =>
                {
                    b.Property<Guid>("Guid");

                    b.Property<int>("AttachmentId");

                    b.Property<string>("AttachmentType");

                    b.Property<Guid?>("CreatedByUserGuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Extension");

                    b.Property<string>("FileName");

                    b.Property<int?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<bool>("IsHome");

                    b.Property<Guid?>("ModifiedByUserGuid");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("OriginName");

                    b.Property<int?>("Ranking");

                    b.Property<string>("StoreDir");

                    b.HasKey("Guid");

                    b.ToTable("ac_photo");
                });

            modelBuilder.Entity("Auction.Entities.User", b =>
                {
                    b.Property<Guid>("Guid");

                    b.Property<Guid?>("AvatorGuid");

                    b.Property<Guid?>("CreatedByUserGuid");

                    b.Property<string>("CreatedByUserName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("LoginName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ModifiedByUserGuid");

                    b.Property<string>("ModifiedByUserName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RealName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserRole");

                    b.HasKey("Guid");

                    b.HasIndex("AvatorGuid");

                    b.ToTable("ac_user");
                });

            modelBuilder.Entity("Auction.Entities.EquipmentPhoto", b =>
                {
                    b.HasOne("Auction.Entities.Equipment", "Equipment")
                        .WithMany("EquipmentPhotos")
                        .HasForeignKey("EquipmentGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Auction.Entities.Photo", "Photo")
                        .WithMany("EquipmentPhotos")
                        .HasForeignKey("PhotoGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Auction.Entities.User", b =>
                {
                    b.HasOne("Auction.Entities.Photo", "Avator")
                        .WithMany()
                        .HasForeignKey("AvatorGuid");
                });
#pragma warning restore 612, 618
        }
    }
}
