// <auto-generated />
using System;
using Auction.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Auction.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Auction.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Guid");

                    b.Property<string>("AuctionHouse");

                    b.Property<string>("City");

                    b.Property<string>("Code");

                    b.Property<string>("Country");

                    b.Property<Guid>("CreatedByUserGuid");

                    b.Property<string>("CreatedByUserName");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<decimal>("DealPrice");

                    b.Property<decimal>("DealPriceRMB");

                    b.Property<int>("Height");

                    b.Property<int>("IsDelete");

                    b.Property<string>("IsPurchase");

                    b.Property<int>("IsSold");

                    b.Property<int>("Long");

                    b.Property<string>("Manufacturer");

                    b.Property<string>("Model");

                    b.Property<Guid?>("ModifiedByUserGuid");

                    b.Property<string>("ModifiedByUserName");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name");

                    b.Property<DateTime>("ProductionDate");

                    b.Property<decimal>("Volume");

                    b.Property<double>("Weight");

                    b.Property<int>("Width");

                    b.Property<DateTime>("WorkingTime");

                    b.HasKey("Guid");

                    b.ToTable("ac_equipment");
                });

            modelBuilder.Entity("Auction.Entities.EquipmentPhoto", b =>
                {
                    b.Property<Guid>("EquipmentGuid");

                    b.Property<Guid>("PhotoGuid");

                    b.Property<DateTime>("CreatedOn");

                    b.HasKey("EquipmentGuid", "PhotoGuid");

                    b.HasIndex("PhotoGuid");

                    b.ToTable("ac_equipment_photo");
                });

            modelBuilder.Entity("Auction.Entities.Photo", b =>
                {
                    b.Property<Guid>("Guid");

                    b.Property<int>("AttachmentId");

                    b.Property<string>("AttachmentType");

                    b.Property<Guid>("CreatedByUserGuid");

                    b.Property<string>("CreatedByUserName");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Extension");

                    b.Property<string>("FileName");

                    b.Property<int>("IsDelete");

                    b.Property<bool>("IsHome");

                    b.Property<Guid?>("ModifiedByUserGuid");

                    b.Property<string>("ModifiedByUserName");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("OriginName");

                    b.Property<int>("Ranking");

                    b.Property<string>("StoreDir");

                    b.HasKey("Guid");

                    b.ToTable("ac_photo");
                });

            modelBuilder.Entity("Auction.Entities.User", b =>
                {
                    b.Property<Guid>("Guid");

                    b.Property<Guid?>("AvatorGuid");

                    b.Property<Guid>("CreatedByUserGuid");

                    b.Property<string>("CreatedByUserName");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IsDelete");

                    b.Property<int>("IsLocked");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ModifiedByUserGuid");

                    b.Property<string>("ModifiedByUserName");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RealName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserRole");

                    b.HasKey("Guid");

                    b.HasIndex("AvatorGuid");

                    b.ToTable("ac_user");
                });

            modelBuilder.Entity("Auction.Entities.EquipmentPhoto", b =>
                {
                    b.HasOne("Auction.Entities.Equipment", "Equipment")
                        .WithMany("EquipmentPhotos")
                        .HasForeignKey("EquipmentGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Auction.Entities.Photo", "Photo")
                        .WithMany("EquipmentPhotos")
                        .HasForeignKey("PhotoGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Auction.Entities.User", b =>
                {
                    b.HasOne("Auction.Entities.Photo", "Avator")
                        .WithMany()
                        .HasForeignKey("AvatorGuid");
                });
#pragma warning restore 612, 618
        }
    }
}
